Protocols/Controllers/EllipticCurvesController.cs
using System;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using EllipticCurves.DataModels.EllipticCurves;
using EllipticCurves.DataModels.FiniteFields;
using EllipticCurves.Helpers;
using Newtonsoft.Json;
using Protocols.Models;
using Protocols.Monitoring;
using SmartParser = Core.Helpers.BigIntegerSmartParser;

namespace Protocols.Controllers
{
    public class EllipticCurvesController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Work()
        {
            return View();
        }

        public ActionResult Help()
        {
            return View();
        }
        
        public string Calculate(string finiteField, string ellipticCurve, string operations)
        {
            Logger.Log.Info($"Calculate: '{finiteField}', '{ellipticCurve}', '{operations}'");
            
            var finiteFieldModel = JsonConvert.DeserializeObject<FiniteFieldModel>(finiteField);
            var ellipticCurveModel = JsonConvert.DeserializeObject<EllipticCurveModel>(ellipticCurve);
            var operationsModels = JsonConvert.DeserializeObject<EllipticCurveOperationModel[]>(operations);
            
            var isPrimeField = finiteFieldModel.Type == "GF(p)";

            try
            {
                var field = isPrimeField
                    ? EllipticParser.ParsePrimeField(finiteFieldModel.Modulus)
                    : EllipticParser.ParseBinaryField(finiteFieldModel.Modulus, finiteFieldModel.ReductionPolynomial);

                var curve = isPrimeField
                    ? EllipticParser.ParsePrimeEllipticCurve(ellipticCurveModel.A, ellipticCurveModel.B, field)
                    : EllipticParser.ParseBinaryEllipticCurve(ellipticCurveModel.A, ellipticCurveModel.B, field);

                return Calculate(curve, operationsModels, field);
            }
            catch (Exception e)
            {
                return $"Ошибка! {e.Message}";
            }
        }

        public string CalculateFromFile(string finiteFieldType, string inputFile)
        {
            Logger.Log.Info($"CalculateFromFile: '{finiteFieldType}', '{inputFile}'");
            
            var isPrimeField = finiteFieldType == "GF(p)";
            var data = inputFile.Split(new[] { "\n", "\r\n"}, StringSplitOptions.RemoveEmptyEntries);
            try
            {
                if (data.Length < 4)
                    throw new Exception("Неверный формат файла");

                FiniteField field;
                if (isPrimeField)
                    field = EllipticParser.ParsePrimeField(data[0]);
                else
                {
                    var fieldParams = data[0].Split(' ');
                    if (fieldParams.Length != 2)
                        throw new Exception("Неверный формат файла");

                    field = EllipticParser.ParseBinaryField(f: fieldParams[1], p: fieldParams[0]);
                }

                var curveParams = data[1].Split(' ');
                if (curveParams.Length != 2)
                    throw new Exception("Неверный формат файла");
                
                var curve = isPrimeField
                    ? EllipticParser.ParsePrimeEllipticCurve(a: curveParams[0], b: curveParams[1], field: field)
                    : EllipticParser.ParseBinaryEllipticCurve(a: curveParams[0], b: curveParams[1], field: field);

                var operationsParams = data[2].Split(' ');
                if (operationsParams.Length != 2)
                    throw new Exception("Неверный формат файла");

                var t = int.Parse(operationsParams[0]);
                var s = int.Parse(operationsParams[1]);

                if (data.Length < t + s + 3)
                    throw new Exception("Неверный формат файла");

                var sumOperations = data.Skip(3).Take(t).Select(ParseSummarizeOperation);
                var mulOperations = data.Skip(3 + t).Take(s).Select(ParseMultiplyOperation);
                
                return Calculate(curve, sumOperations.Union(mulOperations).ToArray(), field);               
            }
            catch (Exception e)
            {
                return $"Ошибка! {e.Message}";
            }
        }

        private static string Calculate(EllipticCurve curve, EllipticCurveOperationModel[] operations, FiniteField field)
        {
            var sb = new StringBuilder();

            for (var i = 0; i < operations.Length; i++)
            {
                var operation = operations[i];
                try
                {
                    switch (operation.Type)
                    {
                        case "+":
                            var a = EllipticParser.ParsePoint(operation.X1, operation.Y1, field);
                            var b = EllipticParser.ParsePoint(operation.X2, operation.Y2, field);
                            var c = curve.Summarize(a, b);
                            sb.AppendLine($"{i+1}. {a} + {b} = {c}");
                            break;
                        case "x":
                            var factor = SmartParser.Parse(operation.Factor);
                            var point = EllipticParser.ParsePoint(operation.X1, operation.Y1, field);
                            var res = curve.Multiply(factor, point);
                            sb.AppendLine($"{i+1}. {factor} x {point} = {res}");
                            break;
                        default:
                            sb.AppendLine($"{i+1}. Неизвестная операция: {operation.Type}");
                            break;
                    }
                }
                catch (Exception e)
                {
                    sb.AppendLine($"{i+1}. {e.Message}");
                }
            }
            
            return sb.ToString();
        }

        private static EllipticCurveOperationModel ParseSummarizeOperation(string data)
        {
            var operationParams = data.Split(' ');
            if (operationParams.Length != 4)
                throw new Exception("Неверный формат файла");
            
            return new EllipticCurveOperationModel
            {
                Type = "+",
                X1 = operationParams[0],
                Y1 = operationParams[1],
                X2 = operationParams[2],
                Y2 = operationParams[3]
            };
        }
        
        private static EllipticCurveOperationModel ParseMultiplyOperation(string data)
        {
            var operationParams = data.Split(' ');
            if (operationParams.Length != 3)
                throw new Exception("Неверный формат файла");
            
            return new EllipticCurveOperationModel
            {
                Type = "x",
                X1 = operationParams[0],
                Y1 = operationParams[1],
                Factor = operationParams[2],
            };
        }
    }
}

Protocols/Views/EllipticCurves/Help.cshtml
@{
    ViewBag.Title = "Как это работает?";
}

<div class="jumbotron">
    <h1>E-Curves</h1>
    <p class="lead">Описание работы сумматора точек эллиптической кривой</p>
</div>

<dl class="dl-horizontal" style="font-size: 18px">
    <dt>Общее</dt>
    <dd>
        Сумматор поддерживает два типа ввода: через интерфейс или через файл.<br>
        Все числа могут быть указаны либо в десятиричной системе счисления (без префикса), либо в шестнадцатиричной (с префиксом 0x).<br>
        Для бинарного поля все числа будут распознаваться как многочлены содержащие iю степень, если соответствующий бит в числе выставлен в 1.
    </dd>
    <br>
    
    <dt>Интерфейс</dt>
    <dd>
        Необходимо выбрать тип конечного поля, который будет использован и указать:<br>
        Для <b>GF(p)</b> порядок поля <b>p</b><br>
        Для <b>GF(2^m)</b> порядок поля <b>2^m</b> и неприводимый многочлен <b>f</b><br>
        <br>
        После этого необходимо указать параметры эллиптической кривой A и B.<br>
        <br>
        Интерфейс позволяет добавлять любое кол-во операций сложения или умножения на число.
        Чтобы изменить операцию, щелкните на ее значок ('+' по умолчанию).<br>
    </dd>
    <br>
    
    <dt>Файл</dt>
    <dd>
        Для корректной работы файл должен быть устроен следующим образом:
        <div class="bs-callout bs-callout-success">
            [Порядок поля] [Неприводимый многочлен (если указано бинарное поле)]<br>
            [A] [B]<br>
            [t] [s]<br>
            [... Далее t строк вида...]<br>
            [X1] [Y1] [X2] [Y2]<br>
            [... Далее s строк вида...]<br>
            [X1] [Y1] [Factor]
        </div>
        Где A и B &mdash; параметры эллиптической кривой, t &mdash; кол-во операций сложения точек, s &mdash; 
        кол-во операций умножения на число. <b>s и t обязательно записываются в десятичной системе счисления!</b><br/>
        Квадратные скобки указаны только в примере для разделения, в исходном файле их быть не должно! 
    </dd>
    <br>
    
    <dt></dt>
    <dd>
        <p><a class="btn btn-primary" href="@Url.Action("Work", "EllipticCurves")">Приступить!</a></p>
    </dd>
</dl>

Protocols/Views/EllipticCurves/Index.cshtml
@{
    ViewBag.Title = "Эллиптические кривые";
}

<div class="jumbotron">
    <h1>E-Curves</h1>
    <p class="lead">
        Сумматор точек эллиптической кривой над GF(p) и GF(2^m)
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Сумматор</h2>
        <p>Сложение и умножение на константу точек эллиптической кривой над GF(p) и GF(2^m)</p>
        <p><a class="btn btn-default" href="@Url.Action("Work", "EllipticCurves")">Приступить! &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Как это работает?</h2>
        <p>Из каких шагов состоит работа, как их выполнять и зачем; что было реализовано и как это посмотреть.</p>
        <p><a class="btn btn-default" href="@Url.Action("Help", "EllipticCurves")">Подробнее &raquo;</a></p>
    </div>
</div>

Protocols/Views/EllipticCurves/Work.cshtml
@{
    ViewBag.Title = "Эллиптические кривые";
}

<script type="text/javascript" src="../../Scripts/Work/ECurvesWork.js"></script>

<div class="jumbotron">
    <h1>E-Curves</h1>
    <p class="lead">
        Сумматор точек эллиптической кривой над GF(p) и GF(2^m)
    </p>
</div>

<h2>Данные</h2>
<div class="form-horizontal">
    <div class="form-group">
        <label for="ModesContainer" class="col-md-2 control-label">Ввод</label>
        <div id="ModesContainer" class="col-sm-10">
            <input type="button" class="btn" onclick="setInputType('Интерфейс')" value="Интерфейс"
                   data-bind="css: {'btn-primary': isUIInputType, 'btn-default' : !isUIInputType() }" />
    
            <input type="button" class="btn" onclick="setInputType('Файл')" value="Файл"
                   data-bind="css: {'btn-primary': isFileInputType, 'btn-default' : !isFileInputType() }" />
                    
            <a class="btn btn-warning" href="@Url.Action("Help", "EllipticCurves")">Помощь</a>
        </div>
    </div>

    <div class="form-group">
        <label for="FieldTypesContainer" class="col-md-2 control-label">Тип поля</label>
        <div id="FieldTypesContainer" class="col-sm-10">
            <input type="button" class="btn" onclick="setFieldType('GF(p)')" value="GF(p)"
                   data-bind="css: {'btn-primary': isPrimeField, 'btn-default' : !isPrimeField() }" />
    
            <input type="button" class="btn" onclick="setFieldType('GF(2^m)')" value="GF(2^m)"
                   data-bind="css: {'btn-primary': isBinaryField, 'btn-default' : !isBinaryField() }" />
        </div>
    </div>

    <div class="form-group" data-bind="visible: isFileInputType">
        <label for="FileContainer" class="col-md-2 control-label"></label>
        <div id="FileContainer" class="col-sm-10">
            <input type="file" id="fileInput" onchange="loadFile()" data-bind="visible: !process()">
            
            <img src="../../Content/Load.gif" style="display: none; width: 27px" alt="<Load>"
                 data-bind="visible: process"/>
        </div>
    </div>
    
    <div class="form-group" data-bind="visible: isUIInputType">
        <label for="Modulus" class="col-md-2 control-label">Поле</label>
        <div id="Modulus" class="col-md-9">
            <div class="col-md-4 padding-less">
                <input type="text" class="form-control col-md-4" placeholder="Введите порядок поля"
                       data-bind="value: modulus">
            </div>

            <div class="col-md-1"></div>

            <div class="col-md-4 padding-less">
                <input type="text" class="form-control col-md-4" placeholder="Введите неприводимый многочлен"
                       data-bind="value: reductionPolynomial, visible: isBinaryField">
            </div>
        </div>
    </div>
    
    <div class="form-group" data-bind="visible: isUIInputType">
        <label for="EllipticCurve" class="col-md-2 control-label">Эллиптическая кривая</label>
        <div id="EllipticCurve" class="col-md-9">
            <div class="col-md-4 padding-less">
                <input type="text" id="EllipticCurveA" class="form-control col-md-4" placeholder="Введите A" data-bind="value: ellipticCurveA">
            </div>
            
            <div class="col-md-1"></div>
            
            <div class="col-md-4 padding-less">
                <input type="text" id="EllipticCurveB" class="form-control col-md-4" placeholder="Введите B" data-bind="value: ellipticCurveB">
            </div>
        </div>
    </div>
</div>

<h2 data-bind="visible: isUIInputType">Операции</h2>
<div class="form-horizontal" data-bind="visible: isUIInputType">
    <div data-bind="foreach: operations">
        <div class="form-group">
            <label class="col-md-2">
                <input type="button" class="btn btn-danger center-block" data-bind="click: $parent.removeOperation" value="Удалить" >
            </label>
            <div class="col-md-9">
                <div class="col-md-4 padding-less">
                    <input type="text" class="form-control col-md-4" placeholder="Введите X1" data-bind="value: x1">
                    <input type="text" class="form-control col-md-4" placeholder="Введите Y1" data-bind="value: y1">
                </div>
                
                <div class="col-md-1">
                    <input type="button" class="btn btn-info" data-bind="click: $parent.changeType, value: type">
                </div>
                
                <div class="col-md-4 padding-less">
                    <input type="text" class="form-control col-md-4" placeholder="Введите X2" data-bind="value: x2, visible: type() == '+'">
                    <input type="text" class="form-control col-md-4" placeholder="Введите Y2" data-bind="value: y2, visible: type() == '+'">
                    <input type="text" class="form-control col-md-4" placeholder="Введите множитель" data-bind="value: factor, visible: type() == 'x'">
                </div>
            </div>
        </div>
    </div>        

    <div class="form-group">
        <label class="col-md-2">
            <input type="button" class="btn btn-success center-block" data-bind="click: addOperation" value="Добавить"/>
        </label>
        <div class="col-sm-10">
            <input type="button" class="btn btn-success" onclick="calculate()" value="Посчитать"
                   data-bind="visible: hasOperations() && !process()"/>
            <img src="../../Content/Load.gif" style="display: none; width: 27px" alt="<Load>"
                 data-bind="visible: process"/>
        </div>
    </div>
</div>

<h2 data-bind="visible: hasResult">Результат</h2>
<div class="bs-callout" 
     data-bind="visible: hasResult, css: {'bs-callout-danger': isResultError, 'bs-callout-success' : !isResultError() }">
    <p data-bind="html: result"></p>
    <input type="button" class="btn btn-primary" onclick="downloadResult()" value="Сохранить в файл" />
</div>

<script>
    ko.applyBindings(data);
</script>