Protocols/Controllers/DistributedCurrencyController.cs
using System;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using Core.Extensions;
using DistributedCurrency.DataBaseModels;
using DistributedCurrency.DataModels;
using DistributedCurrency.Factories;
using DistributedCurrency.Workers;
using Newtonsoft.Json;

namespace Protocols.Controllers
{
    public class DistributedCurrencyController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NewWallet()
        {
            return View();
        }

        public ActionResult Help()
        {
            return View();
        }

        public Guid CreateWallet(string surname, string name)
        {
            var wallet = WalletFactory.Create();
            var contact = ContactsFactory.Create(wallet, $"{name} {surname}");

            using (var context = new DistributedCurrencyContext())
            {
                context.Wallets.Add(wallet);
                context.Contacts.Add(contact);
                context.SaveChanges();
            }

            return wallet.Id;
        }

        public ActionResult Work(Guid? id)
        {
            using (var context = new DistributedCurrencyContext())
            {
                var contact = id.HasValue ? context.Read<Contact>(id.Value) : context.Contacts.GetRandomElement();
                ViewBag.ContactId = contact.Id.ToString("D").ToUpper();
                ViewBag.ContactName = contact.Name;

                var publicKey = contact.PublicKey;
                var base64PublicKey = Convert.ToBase64String(publicKey);
                ViewBag.ContactPublicKey = Regex
                                            .Matches(base64PublicKey, ".{5}")
                                            .Select(m => m.Value)
                                            .JoinStrings(" ");

                ViewBag.TransactionsIds = context
                                            .Transactions
                                            .Where(t => (t.SenderPublicKey == publicKey && t.SurplusCoins > 0) || 
                                                        (t.ReciverPublicKey == publicKey && t.Coins > 0) ||
                                                        (t.MinerPublicKey == publicKey && t.MinerReward > 0))
                                            .Select(t => t.Id)
                                            .ToArray();
            }

            return View();
        }

        public string GetTransaction(Guid id)
        {
            using (var context = new DistributedCurrencyContext())
                return JsonConvert.SerializeObject(context.Read<Transaction>(id));
        }

        public string CreateTransfer(string senderPublicKey, string destPublicKey, Guid sourceId, int coins)
        {
            TransactCreationResult result;

            try
            {
                var senderKey = Convert.FromBase64String(senderPublicKey.Replace(" ", ""));
                var distKey = Convert.FromBase64String(destPublicKey.Replace(" ", ""));

                var trans = TransactionFactory.CreateTransfer(senderKey, distKey, sourceId, coins);
                var randomPublicPrivateKey = GetRandomPublicPrivateKeyExcept(senderKey);

                TransactionVerifier.Verify(trans, randomPublicPrivateKey);
                Miner.CloseTransaction(trans, randomPublicPrivateKey);

                using (var context = new DistributedCurrencyContext())
                {
                    context.Transactions.Add(trans);
                    context.SaveChanges();
                }

                result = new TransactCreationResult(trans);
            }
            catch (Exception ex)
            {
                result = new TransactCreationResult(ex);
            }

            return JsonConvert.SerializeObject(result);
        }

        public string CreateUnion(string senderPublicKey, Guid sourceId, Guid extraSourceId)
        {
            TransactCreationResult result;

            try
            {
                var senderKey = Convert.FromBase64String(senderPublicKey.Replace(" ", ""));

                var trans = TransactionFactory.CreateUnion(senderKey, sourceId, extraSourceId);
                var randomPublicPrivateKey = GetRandomPublicPrivateKeyExcept(senderKey);

                TransactionVerifier.Verify(trans, randomPublicPrivateKey);
                Miner.CloseTransaction(trans, randomPublicPrivateKey);

                using (var context = new DistributedCurrencyContext())
                {
                    context.Transactions.Add(trans);
                    context.SaveChanges();
                }

                result = new TransactCreationResult(trans);
            }
            catch (Exception ex)
            {
                result = new TransactCreationResult(ex);
            }

            return JsonConvert.SerializeObject(result);
        }

        private byte[] GetRandomPublicPrivateKeyExcept(byte[] senderPublicKey)
        {
            using (var context = new DistributedCurrencyContext())
            {
                var allPublicPrivateKeysExceptSenderQuery =
                    from c in context.Contacts
                    join w in context.Wallets on c.Id equals w.Id
                    where c.PublicKey != senderPublicKey
                    select w.PublicPrivateKey;

                return allPublicPrivateKeysExceptSenderQuery.GetRandomElement();
            }
        }
    }
}

Protocols/Views/DistributedCurrency/Help.cshtml
@using DistributedCurrency
@{
    ViewBag.Title = "Как это работает?";
}

<div class="jumbotron">
    <h1>D-Currency</h1>
    <p class="lead">Описание протокола распределенной валюты</p>
</div>

<dl class="dl-horizontal" style="font-size: 18px">
    <dt>Общее</dt>
    <dd>
        Протокол позволяет обмениваться криптовалютой между кошельками посредством транзакций.
        Все, что нужно знать &mdash; открытый ключ кошелька, на который Вы хотите переслать свои монетки.
        Будьте внимательны &mdash; транзакции нельзя отменить!
    </dd>
    <br/>

    <dt>Кошелек</dt>
    <dd>
        Это комбинация открытого и закрытого ключа (использован RSA с 1024битным ключом).
        Открытый ключ отображается как строка в Base64, где каждые 5 символов разделены пробелом.
        Именно в таком формате его и нужно вводить при создании транзакции.
        <br/>
        <br/>
        Каждому кошельку соответствует уникальный ID, его можно найти на странице кошелька.
        <br/>
        В системе уже существуют несколько кошельков, можно использовать @Html.ActionLink("любой из них", "Work", "DistributedCurrency"), либо @(Html.ActionLink("создать новый", "NewWallet", "DistributedCurrency")).
        <br/>
        Чтобы открыть конкретный кошелек, добавьте в адресной строке его уникальный ID
        <br />
        (Например, @Html.ActionLink("Кошелек Шерлока Холмса", "Work", "DistributedCurrency", new { id = DCSecret.SherlockHolmesWalletId }, null))
    </dd>
    <br/>

    <dt>Транзакции</dt>
    <dd>
        Существует 2 типа транзакций: перевод и объединение.
        <br />
        После создания транзакция отдается подтверждающим &mdash; они определяют, что начальное состояние корректно (указан допустимый перевод 
        и правильная сдача, объединение веток с общим корнем приводит к выбору наиболее длинной) и подписывают транзакцию.
        <br />
        Затем транзакция отдается майнерам &mdash; они превращают все данные в байтовый массив и складывают их по модулю 256. После этого находят
        такой байт, чтобы итоговая сумма была равна 0. Для имитации нагруженности, это делается последовательно с 0 до 255 со случайной задержкой
        на каждом шаге.
        <br />
        После закрытия транзакция считается выполненной, ее можно использовать далее.
    </dd>
    <br />

    <dt>Начало цепочки</dt>
    <dd>
        Началом цепочки транзакций служит транзакция с предком 00000000-0000-0000-0000-000000000000
    </dd>
    <br />

    <dt></dt>
    <dd>
        <p><a class="btn btn-primary" href="@Url.Action("Work", "DistributedCurrency")">Приступить!</a></p>
    </dd>
</dl>

Protocols/Views/DistributedCurrency/Index.cshtml
@{
    ViewBag.Title = "Распределенная валюта";
}

<div class="jumbotron">
    <h1>D-Currency</h1>
    <p class="lead">
        Распределенная валюта с возможностью перевода и объединения транзакций; 
        алгоритм выбора самой длинной цепочки в случае объединения транзакций с общим предком.
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Создать кошелек</h2>
        <p>Для работы с криптовалютой необходим собственный кошелек. Все, что необходимо сделать - указать имя.</p>
        <p><a class="btn btn-default" href="@Url.Action("NewWallet", "DistributedCurrency")">Далее &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Приступить к работе</h2>
        <p>Система случайным образом выберет существующий кошелек и откроет все операции его владельца.</p>
        <p><a class="btn btn-default" href="@Url.Action("Work", "DistributedCurrency")">Далее &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Как это работает?</h2>
        <p>Из каких шагов состоит работа, как их выполнять и зачем; что было реализовано и как это посмотреть.</p>
        <p><a class="btn btn-default" href="@Url.Action("Help", "DistributedCurrency")">Подробнее &raquo;</a></p>
    </div>
</div>

Protocols/Views/DistributedCurrency/NewWallet.cshtml
@{
    ViewBag.Title = "Новый кошелек";
}

<script type="text/javascript" src="../../Scripts/Work/CreateWallet.js"></script>

<div class="jumbotron">
    <h1>Создание кошелька</h1>
</div>

<div class="row">
    <div class="col-md-8" method="post">
        <div class="form-group">
            <span class="lead">Все поля обязательны!</span>
        </div>

        <div class="form-group" data-bind="css: { 'has-error' : Surname() === '', 'has-success' : Surname() !== '' }">
            <input type="text" class="form-control" id="Surname" data-bind="value: Surname" placeholder="Введите фамилию">
        </div>

        <div class="form-group" data-bind="css: { 'has-error' : Name() === '', 'has-success' : Name() !== '' }">
            <input type="text" class="form-control" id="Name" data-bind="value: Name" placeholder="Введите имя">
        </div>

        <input type="button" class="btn btn-primary" value="Создать кошелек" onclick="createWallet()" data-bind="visible: !CreationInProgress()">
        <img src="../../Content/Load.gif" width="27" data-bind="visible: CreationInProgress()" alt="<Load>" style="display: none" />
    </div>
</div>

<script>
    ko.applyBindings(data);
</script>

Protocols/Views/DistributedCurrency/Work.cshtml
@{
    ViewBag.Title = "Операции";
}

<script type="text/javascript" src="../../Scripts/Work/CurrencyWork.js"></script>

<div class="jumbotron">
    <h1>@ViewBag.ContactName</h1>

    <dl class="dl-horizontal" style="font-size: 131%">
        <dt style="text-align: left">Кошелек</dt>
        <dd id="WalletId" style="font-family: monospace;">@ViewBag.ContactId</dd>
        <dt style="text-align: left">Открытый ключ</dt>
        <dd id="WalletPublicKey" style="font-family: monospace;">@ViewBag.ContactPublicKey</dd>
    </dl>
</div>

<h2>Создать транзакцию</h2>
<div class="form-horizontal">
    <div class="form-group">
        <label for="ModesContainer" class="col-md-2 control-label">Режим</label>
        <div id="ModesContainer">
            <div class="col-sm-10">
                <input type="button" class="btn" onclick="setMode('Перевести')" value="Перевод"
                       data-bind="css: {'btn-primary': IsTransfer(), 'btn-default' : !IsTransfer() }"/>

                <input type="button" class="btn" onclick="setMode('Объединить')" value="Объединение"
                       data-bind="css: {'btn-primary': IsUnion(), 'btn-default' : !IsUnion() }"/>
                
                <a class="btn btn-warning" href="@Url.Action("Help", "DistributedCurrency")">Помощь</a>
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <label for="SourceId" class="col-md-2 control-label">Исходная транзакция</label>
        <div class="col-sm-10">
            <input type="text" id="SourceId" class="form-control" placeholder="Введите идентификатор"
                   data-bind="value: SourceId">
        </div>
    </div>

    <div class="form-group" data-bind="visible: IsUnion()" style="display: none">
        <label for="ExtraSourceId" class="col-md-2 control-label">Доп. транзакция</label>
        <div class="col-sm-10">
            <input type="text" id="ExtraSourceId" class="form-control" placeholder="Введите идентификатор"
                   data-bind="value: ExtraSourceId">
        </div>
    </div>
    
    <div class="form-group" data-bind="visible: IsTransfer()">
        <label for="DestPublicKey" class="col-md-2 control-label">Получатель</label>
        <div class="col-sm-10">
            <input type="text" id="DestPublicKey" class="form-control" placeholder="Введите открытый ключ"
                   data-bind="value: DestPublicKey">
        </div>
    </div>
    
    <div class="form-group" data-bind="visible: IsTransfer()">
        <label for="Coins" class="col-md-2 control-label">Перевести</label>
        <div class="col-sm-10">
            <input type="text" id="Coins" class="form-control" placeholder="0"
                   data-bind="value: Coins">
        </div>
    </div>
    
    <div class="form-group" data-bind="visible: Error() !== ''">
        <div class="col-md-offset-2 col-sm-10">
            <span class="text-danger" data-bind="text: Error"></span>
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-md-offset-2 col-sm-10">
            <input type="button" class="btn btn-success" onclick="processTransact()" data-bind="value: Mode, visible: !ProcessTransact()" />
            <img src="../../Content/Load.gif" style="display: none; width: 27px" alt="<Load>" data-bind="visible: ProcessTransact" />
        </div>
    </div>
</div>

<h2>Список транзакций</h2>
<table id="TransactionTable" class="table table-condensed table-hover">
    <tr id="TableHeader">
        <th></th>
        <th>Идентификатор транзакции</th>
    </tr>
    
    @foreach (var t in (Guid[])ViewBag.TransactionsIds)
    {
        <tr onclick="showhide('@t')">
            <td></td>
            <td>@t</td>
        </tr>
        <tr id="@t" style="display: none">
            <td class="text-center" colspan="2">
                <img id="load_@(t)" style="display: none; width: 27px" src="../../Content/Load.gif" alt="<Load>" />
                <div id="data_@(t)" class="text-left" style="display: none"></div>
            </td>
        </tr>
    }
</table>

<script>
    data.WalletPublicKey = $('#WalletPublicKey').text();
    ko.applyBindings(data);
</script>