Protocols/Controllers/AnonymousCurrencyController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AnonymousCurrency;
using AnonymousCurrency.DataBaseModels;
using AnonymousCurrency.DataModels;
using AnonymousCurrency.Enums;
using AnonymousCurrency.Extensions;
using AnonymousCurrency.Factories;
using AnonymousCurrency.Workers;
using Core.Cryptography;
using Core.Extensions;
using Newtonsoft.Json;
using DataBase = Core.Workers.DataBase<AnonymousCurrency.Workers.AnonymousCurrencyContext>;

namespace Protocols.Controllers
{
    public class AnonymousCurrencyController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NewAccount()
        {
            return View();
        }

        public ActionResult Help()
        {
            return View();
        }

        public Guid CreateAccount(string nickname)
        {
            using (var bank = new Bank())
                return bank.RegisterCustomer(nickname);
        }

        public ActionResult Work(Guid? id)
        {
            using (var context = new AnonymousCurrencyContext())
            {
                var account = id.HasValue ? context.Read<BankCustomer>(id.Value) : context.BankCustomers.GetRandomElement();
                ViewBag.AccountId = account.Id;
                ViewBag.AccountName = account.NickName;
                ViewBag.AccountBalance = account.Balance;

                ViewBag.OpenedEnvelopesIds = context
                                                .Envelopes
                                                .Where(e => e.OwnerId == account.Id && e.State == EnvelopeState.Opened)
                                                .Select(t => t.Id)
                                                .ToArray();

                ViewBag.SealedEnvelopesIds = context
                                                .Envelopes
                                                .Where(e => e.OwnerId == account.Id && e.State == EnvelopeState.Sealed)
                                                .Select(t => t.Id)
                                                .ToArray();
            }

            return View();
        }

        public string GetEnvelope(Guid id)
        {
            return JsonConvert.SerializeObject(DataBase.Read<SignedEnvelope>(id));
        }

        public string CreateSealedEnvelope(Guid userId, int amount, int cheatAmount)
        {
            try
            {
                using (var bank = new Bank())
                {
                    var range = Enumerable.Range(0, ACSecret.EnvelopeSignCount).ToArray();
                    var cheatIdx = new Random().Next(ACSecret.EnvelopeSignCount); 
                    var csps = range.Select(i => new {i, csp = new RSACryptography()}).ToArray();
                    var envelopes = csps
                        .Select(csp => EnvelopeFactory.CreateBankCheckingEnvelope(csp.csp, userId, amount + (csp.i == cheatIdx? cheatAmount : 0)))
                        .ToArray();

                    var application = new CustomerApplication
                    {
                        CustomerId = userId,
                        Balance = amount,
                        Envelopes = envelopes
                    };

                    var operation = bank.StartSignEnvelopeOperation(application);
                    var publicPrivateKeys = operation.EnvelopesToCheck.Select(i => csps[i].csp).ToArray();
                    var signedEnvelope = operation.CheckAndSignEnvelope(publicPrivateKeys);

                    signedEnvelope.PublicPrivateKey = csps[operation.EnvelopeToSign].csp.PublicPrivateKey;
                    signedEnvelope.State = EnvelopeState.Sealed;
                    DataBase.Write(signedEnvelope);

                    return $"Успех! Создан конверт {signedEnvelope.Id} с {amount + cheatAmount}";
                }
            }
            catch (Exception e)
            {
                return $"Ошибка! {e.Message}";
            }
        }

        public string Pay(Guid userId, Guid envelopeId, Guid reciverId)
        {
            try
            {
                var envelope = DataBase.Read<SignedEnvelope>(envelopeId);
                if (envelope.OwnerId != userId)
                    throw new Exception("Этот конверт Вам не принадлежит!");
                if (envelope.State != EnvelopeState.Sealed)
                    throw new Exception("Тратить можно только закрытые конверты!");

                var envelopeToCheck = EnvelopeFactory.CreateSellerCheckingEnvelope(envelope);
                var payOperation = new PayOperation(envelopeToCheck);
                var sidx = payOperation.SecretNumber;
                var encryptedSecret = envelope.EnumerateSecrets().ElementAt(sidx);
                var newSignedEnvelope = payOperation.Exec(encryptedSecret);
                newSignedEnvelope.OwnerId = reciverId;
                DataBase.Write(newSignedEnvelope);

                return $"Успех! Конверт потрачен - в {newSignedEnvelope.Id}; узнан секрет {sidx}";
            }
            catch (Exception e)
            {
                return $"Ошибка! {e.Message}";
            }
        }

        public string Deposite(Guid userId, Guid envelopeId)
        {
            try
            {
                var envelope = DataBase.Read<SignedEnvelope>(envelopeId);
                if (envelope.OwnerId != userId)
                    throw new Exception("Этот конверт Вам не принадлежит!");
                if (envelope.State != EnvelopeState.Opened)
                    throw new Exception("Класть на счет можно только открытые конверты!");

                using (var bank = new Bank())
                    return $"Успех! На ваш счет добавлено: {bank.AddDeposite(envelope)}";
            }
            catch (Exception e)
            {
                return $"Ошибка! {e.Message}";
            }
        }
    }
}

Protocols/Views/AnonymousCurrency/Help.cshtml
@{
    ViewBag.Title = "Как это работает?";
}

<div class="jumbotron">
    <h1>A-Currency</h1>
    <p class="lead">Описание протокола анонимной валюты</p>
</div>

<dl class="dl-horizontal" style="font-size: 18px">
    <dt>Общее</dt>
    <dd>
        Банк предоставляет услуги выдачи анонимных конвертов, позволяющих клиентам банка обмениваться между собой деньгами,
        скрывая свою личность, но лишь до тех пор, пока клиенты честны: не изготавливают дубликатов конвертов и не пытаются
        дважды получить от банка деньги по одному и тому же конверту. 
    </dd>
    <br/>
    
    <dt>Счет в банке</dt>
    <dd>
        Это комбинация уникального идентификатора, никнейма и баланса. <br/>
        Счет можно @Html.ActionLink("создать", "NewAccount", "AnonymousCurrency"), 
        или использовать @(Html.ActionLink("любой существующий", "Work", "AnonymousCurrency")).
    </dd>
    <br />

    <dt>Конверт</dt>
    <dd>
        В первую очередь &mdash; это набор из уникального идентификатора конверта и суммы. <br />
        Они неизвестны никому, кроме автора конверта, т.к. зашифрованы (поле EncryptedContent).<br/>
        Для того, чтобы подтвердить валидность этих данных, они подписаны банком (поле EncryptedContentSign).<br/>
        <br/>
        Также в конверте есть 10 секретов &mdash; каждые 2 из которых позволят вскрыть личность автора, 
        если он поступит нечестно: начнет копировать конверт и раздавать всем копии.<br/>
        Секреты также зашифрованы (поле EncryptedSecrets) и подписаны банком (поле EncryptedSecretsSigns).<br/>
        <br/>
        Последним в конверте хранится ключ, которым зашифрованы поля данных.<br/>
        <br/>
        Конверт может быть либо <b>закрытым</b> &mdash; хранящимся у автора конверта (и содержащим 10 секретов), 
        либо <b>открытым</b> &mdash; переданным автором другому участнику обмена [<i>продавцу</i>] (и содержащим 1 секрет).
    </dd>
    <br/>

    <dt>Создание конверта</dt>
    <dd>
        Клиент банка генерирует 10 разных конвертов, у каждого из которых разные:<br/>
        <ul>
            <li>Идентификаторы</li>
            <li>Секреты</li>
            <li>Ключи шифрования</li>
        </ul>
        И одинаковые (в идеале) суммы.<br/>
        После этого отправляет банку запрос на подпись: все 10 конвертов, но без ключа шифрования.<br/>
        Банк случайным образом выбирает 9 конвертов и просит автора выслать 9 ключей шифрования.<br/>
        После этого банк "вскрывает" 9 конвертов &mdash; расшифровывает данные и секреты. Если данные соответствуют тому,
        что указано в запросе, а секреты принадлежат вскрытому конверту и автору запроса, банк подписывает содержание десятого
        конверта и каждый его секрет в отдельности, после чего отдает данные автору, снимая с его счета сумму, 
        указанную в запросе.<br/>
        Безусловно, банк показывает ошибку, если обнаружит "поддельный" конверт, однако никаких санкций за это пока 
        не предусмотрено.
    </dd>
    <br />

    <dt>Секрет</dt>
    <dd>
        Секрет содержит уникальный идентификатор конверта, а также случайные коэффиценты прямой <b>kx + b</b>, 
        проходящую через "точку", обозначающую автора. Для получения этой "точки" берется его уникальный идентификатор
        (16 байт) и делится пополам: первые 8 байт это точка <b>x</b>, вторые 8 байт &mdash; точка <b>y</b>.<br/>
        Каждый секрет сериализуется в виде байт, которые шифруются секретным ключом конверта, после чего конкатинируются
        в единую строку.
    </dd>
    <br />

    <dt>Передача конверта</dt>
    <dd>
        Автор конверта передает продавцу:<br/>
        <ul>
            <li>Зашифрованные контент, подписанный банком</li>
            <li>10 банковских подписей всех секретов в конверте (конкатинированных в единую строку)</li>
            <li>Ключ шифрования</li>
        </ul>
        Продавец может проверить, что хранится внутри конверта, если его устраивает содержимое &mdash; 
        он говорит автору одно случайное число, секрет с этим номером автор и передает продавцу.<br/>
        С этого момента конверт считается открытым.
    </dd>
    <br />
    
    <dt>Положить на счет</dt>
    <dd>
        Продавец может прийти в банк и положить на свой счет деньги из конверта.<br/>
        Банк убеждается, что все подписи валидны, а уникальный идентификатор не был использован ранее.<br/>
        Если обнаруживается, что данный конверт уже был использован, запрашивается узнанный продавцом секрет &mdash;
        если сжульничал автор конверта, то скорее всего секреты не совпадут и по 2 разным прямым можно вычислить точку
        пересечения &mdash; уникальный идентификатор автора. Если же секреты совпадут, то считается, что сжульничал продавец,
        которого тут же ловят за руку.
    </dd>
    <br />
    
    <dt></dt>
    <dd>
        <p><a class="btn btn-primary" href="@Url.Action("Work", "AnonymousCurrency")">Приступить!</a></p>
    </dd>
</dl>

Protocols/Views/AnonymousCurrency/Index.cshtml
@{
    ViewBag.Title = "Анонимная валюта";
}

<div class="jumbotron">
    <h1>A-Currency</h1>
    <p class="lead">
        Анонимная валюта, скрывающая личность того, кто использует ее честно.
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Создать счет</h2>
        <p>Для работы необходим счет в банке. Все, что необходимо сделать - указать свой никнейм.</p>
        <p><a class="btn btn-default" href="@Url.Action("NewAccount", "AnonymousCurrency")">Далее &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Приступить к работе</h2>
        <p>Система случайным образом выберет существующий счет и откроет все операции его владельца.</p>
        <p><a class="btn btn-default" href="@Url.Action("Work", "AnonymousCurrency")">Далее &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Как это работает?</h2>
        <p>Из каких шагов состоит работа, как их выполнять и зачем; что было реализовано и как это посмотреть.</p>
        <p><a class="btn btn-default" href="@Url.Action("Help", "AnonymousCurrency")">Подробнее &raquo;</a></p>
    </div>
</div>

Protocols/Views/AnonymousCurrency/NewAccount.cshtml
@{
    ViewBag.Title = "Новый счет";
}

<script type="text/javascript" src="../../Scripts/Work/CreateAccount.js"></script>

<div class="jumbotron">
    <h1>Создание счета</h1>
    <p class="lead">Банк гарантирует Вашу анонимность до тех пор, пока Вы не нарушаете его правил!</p>
</div>

<div class="row">
    <div class="col-md-8" method="post">
        <div class="form-group">
            <span class="lead">Все поля обязательны!</span>
        </div>

        <div class="form-group" data-bind="css: { 'has-error' : Nickname() === '', 'has-success' : Nickname() !== '' }">
            <input type="text" class="form-control" id="Nickname" data-bind="value: Nickname" placeholder="Введите никнейм">
        </div>

        <input type="button" class="btn btn-primary" value="Стать клиентом!" onclick="createAccount()" data-bind="visible: !CreationInProgress()">
        <img src="../../Content/Load.gif" width="27" data-bind="visible: CreationInProgress()" alt="<Load>" style="display: none" />
    </div>
</div>

<script>
    ko.applyBindings(data);
</script>

Protocols/Views/AnonymousCurrency/Work.cshtml
@{
    ViewBag.Title = "Операции";
}

<script type="text/javascript" src="../../Scripts/Work/ACurrencyWork.js"></script>

<div class="jumbotron">
    <h1>Добро пожаловать!</h1>
    <dl class="dl-horizontal" style="font-size: 150%">
        <dt style="text-align: left">Аноним:</dt>
        <dd style="font-family: monospace;">@ViewBag.AccountName</dd>
        <dt style="text-align: left">Счет:</dt>
        <dd style="font-family: monospace;">@ViewBag.AccountId</dd>
        <dt style="text-align: left">На счете:</dt>
        <dd style="font-family: monospace;" data-bind="text: AccountBalance"></dd>
    </dl>
</div>

<div class="bs-callout" 
     data-bind="visible: HasResult, css: {'bs-callout-danger': IsResultError, 'bs-callout-success' : !IsResultError() }">
    <h4 data-bind="text: ResultHeader"></h4>
    <p data-bind="text: ResultText"></p>
</div>

<h2>Управление</h2>
<div class="form-horizontal">
    <div class="form-group">
        <label for="ModesContainer" class="col-md-2 control-label">Операция</label>
        <div id="ModesContainer">
            <div class="col-sm-10">
                <input type="button" class="btn" onclick="setMode('Получить конверт')" value="Снять со счета"
                       data-bind="css: {'btn-primary': IsWithdrawMode(), 'btn-default' : !IsWithdrawMode() }" />

                <input type="button" class="btn" onclick="setMode('Заплатить')" value="Заплатить"
                       data-bind="css: {'btn-primary': IsPayMode(), 'btn-default' : !IsPayMode() }" />
                
                <input type="button" class="btn" onclick="setMode('Положить')" value="Положить на счет"
                       data-bind="css: {'btn-primary': IsDepositMode(), 'btn-default' : !IsDepositMode() }" />
                
                <a class="btn btn-warning" href="@Url.Action("Help", "AnonymousCurrency")">Помощь</a>
            </div>
        </div>
    </div>
    
    <div class="form-group" data-bind="visible: IsWithdrawMode">
        <label for="Amount" class="col-md-2 control-label">Сумма</label>
        <div class="col-sm-10">
            <input type="text" id="Amount" class="form-control" placeholder="0" data-bind="value: Amount">
        </div>
    </div>
    
    <div class="form-group" data-bind="visible: IsWithdrawMode">
        <label for="Cheat" class="col-md-2 control-label">Смухлевать на</label>
        <div class="col-sm-10">
            <input type="text" id="Cheat" class="form-control" placeholder="0" data-bind="value: CheatAmount">
        </div>
    </div>
    
    <div class="form-group" data-bind="visible: !IsWithdrawMode()">
        <label for="EnvelopeID" class="col-md-2 control-label">Конверт</label>
        <div class="col-sm-10">
            <input type="text" id="EnvelopeID" class="form-control" placeholder="Введите идентификатор" 
                   data-bind="value: EnvelopeID">
        </div>
    </div>
    
    <div class="form-group" data-bind="visible: IsPayMode">
        <label for="ReciverID" class="col-md-2 control-label">Получатель</label>
        <div class="col-sm-10">
            <input type="text" id="ReciverID" class="form-control" placeholder="Введите идентификатор"
                   data-bind="value: ReciverID">
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-md-offset-2 col-sm-10">
            <input type="button" class="btn btn-success" onclick="process()" data-bind="value: Mode, visible: !Process()" />
            <img src="../../Content/Load.gif" style="display: none; width: 27px" alt="<Load>" data-bind="visible: Process" />
        </div>
    </div>
</div>

<h2>Список конвертов</h2>
<table id="EnvelopeTable" class="table table-condensed table-hover">
    <tr id="TableHeader">
        <th></th>
        <th>Идентификатор конверта</th>
        <th>Состояние конверта</th>
    </tr>

    @foreach (var t in (Guid[])ViewBag.SealedEnvelopesIds)
    {
        <tr onclick="showhide('@t')">
            <td></td>
            <td>@t</td>
            <td>Запечатанный</td>
        </tr>
        <tr id="@t" style="display: none">
            <td class="text-center" colspan="3">
                <img id="load_@(t)" style="display: none; width: 27px" src="../../Content/Load.gif" alt="<Load>" />
                <div id="data_@(t)" class="text-left" style="display: none"></div>
            </td>
        </tr>
    }
    
    @foreach (var t in (Guid[])ViewBag.OpenedEnvelopesIds)
    {
        <tr onclick="showhide('@t')">
            <td></td>
            <td>@t</td>
            <td>Открытый</td>
        </tr>
        <tr id="@t" style="display: none">
            <td class="text-center" colspan="3">
                <img id="load_@(t)" style="display: none; width: 27px" src="../../Content/Load.gif" alt="<Load>" />
                <div id="data_@(t)" class="text-left" style="display: none"></div>
            </td>
        </tr>
    }
</table>

<script>
    data.UserId = "@ViewBag.AccountId";
    data.AccountBalance = ko.observable("@ViewBag.AccountBalance");

    ko.applyBindings(data);
</script>