Protocols/Controllers/ProbabilisticEncryptionController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Core.Helpers;
using Newtonsoft.Json;
using ProbabilisticEncryption.DataBaseModels;
using ProbabilisticEncryption.Workers;
using DataBase = Core.Workers.DataBase<ProbabilisticEncryption.Workers.ProbabilisticEncryptionContext>;

namespace Protocols.Controllers
{
    public class ProbabilisticEncryptionController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Work()
        {
            return View();
        }

        public ActionResult Help()
        {
            return View();
        }

        public string LoadKeyContainersIds()
        {
            try
            {
                using (var context = new ProbabilisticEncryptionContext())
                {
                    var keys = context
                                    .KeyContainers
                                    .Select(k => k.Id)
                                    .ToArray();

                    return JsonConvert.SerializeObject(keys);
                }
            }
            catch (Exception e)
            {
                return $"Ошибка! {e.Message}";
            }
        }

        public string LoadEncryptedMessagesIds()
        {
            try
            {
                using (var context = new ProbabilisticEncryptionContext())
                {
                    var keys = context
                                    .EncryptedMessages
                                    .Select(k => k.Id)
                                    .ToArray();

                    return JsonConvert.SerializeObject(keys);
                }
            }
            catch (Exception e)
            {
                return $"Ошибка! {e.Message}";
            }
        }

        public string LoadKeyContainer(Guid id)
        {
            try
            {
                var keyContainer = DataBase.Read<KeyContainer>(id);
                return JsonConvert.SerializeObject(keyContainer);
            }
            catch (Exception e)
            {
                return $"Ошибка! {e.Message}";
            }
        }

        public string LoadEncryptedMessage(Guid id)
        {
            try
            {
                var encryptedMessage = DataBase.Read<EncryptedMessageContainer>(id);
                return JsonConvert.SerializeObject(encryptedMessage);
            }
            catch (Exception e)
            {
                return $"Ошибка! {e.Message}";
            }
        }

        public string CreateKeyContainer()
        {
            try
            {
                using (var timeMeasurer = new TimeMeasurer())
                {
                    KeyContainer key;
                    using (timeMeasurer.StartOperation("1. Генерация контейнера"))
                        key = KeyContainerFactory.CreateNew();

                    using (timeMeasurer.StartOperation("2. Запись контейнера в бд"))
                        DataBase.Write(key);

                    return $"Успех! Контейнер {key.Id} сгенерирован!\n{timeMeasurer.Results}";
                }
            }
            catch (Exception e)
            {
                return $"Ошибка! {e.Message}";
            }
        }

        public string CreateEncryptedMessage(Guid keyId, string message)
        {
            try
            {
                using (var timeMeasurer = new TimeMeasurer())
                {
                    KeyContainer key;
                    using (timeMeasurer.StartOperation("1. Чтение ключа из бд"))
                        key = DataBase.Read<KeyContainer>(keyId);

                    EncryptedMessageContainer emsg;
                    using (timeMeasurer.StartOperation("2. Шифрование"))
                        emsg = ProbabilisticCryptoProvider.Encrypt(key, message);

                    using (timeMeasurer.StartOperation("3. Запись зашифрованного сообщения в бд"))
                        DataBase.Write(emsg);

                    return $"Успех! Сообщение {emsg.Id} зашифровано!\n{timeMeasurer.Results}";
                }
            }
            catch (Exception e)
            {
                return $"Ошибка! {e.Message}";
            }
        }

        public string DecryptMessage(Guid keyId, Guid messageId)
        {
            try
            {
                using (var timeMeasurer = new TimeMeasurer())
                {
                    KeyContainer key;
                    using (timeMeasurer.StartOperation("1. Чтение контейнера ключа из бд"))
                        key = DataBase.Read<KeyContainer>(keyId);

                    EncryptedMessageContainer emsg;
                    using (timeMeasurer.StartOperation("2. Чтение зашифрованного сообщения из бд"))
                        emsg = DataBase.Read<EncryptedMessageContainer>(messageId);

                    string msg;
                    using (timeMeasurer.StartOperation("3. Расшифрование"))
                        msg = ProbabilisticCryptoProvider.Decrypt(key, emsg);

                    return $"Успех! Сообщение {emsg.Id} расшифровано!\n{timeMeasurer.Results}\n\nСодержание:\n{msg}";
                }
            }
            catch (Exception e)
            {
                return $"Ошибка! {e.Message}";
            }
        }
    }
}

Protocols/Views/ProbabilisticEncryption/Help.cshtml
@using ProbabilisticEncryption
@{
    ViewBag.Title = "Как это работает?";
}

<div class="jumbotron">
    <h1>P-Encrypt</h1>
    <p class="lead">Описание протокола вероятностного шифрования</p>
</div>

<dl class="dl-horizontal" style="font-size: 18px">
    <dt>Общее</dt>
    <dd>
        Протокол позволяет шифровать и дешифровать сообщения при помощи генератора пседвдослучайных чисел 
        Blum &mdash; Blum &mdash; Shub (BBS): это позволяет каждый раз преобразовывать один и тот же открытый 
        текст в разный шифр текст.
    </dd>
    <br/>
    
    <dt>Секретный ключ</dt>
    <dd>
        Это два простых числа Блюма &mdash; P (@PESecret.BytesCountP-байтное) и Q(@PESecret.BytesCountQ-байтное)
    </dd>
    <br />

    <dt>Шифрование</dt>
    <dd>
        Генератор BBS инициализируется P и Q (из секретного ключа), их произведением N, 
        а также X0 &mdash; квадратичным остатком по модулю N случайного числа, взаимопростого с N.
        После этого каждый бит открытого текста суммируется по модулю 2 с выходом генератора. 
        <br/>
        <br/>
        Поскольку каждое i-е значение генератора можно вычислить независимо от остальных значений, 
        реализовано многопоточное шифрование.
        <br/>
        <br/>
        В конец сообщения добавляется Xt, где t-1 &mdash; длина сообщения.
        <br />
        Поскольку генератор безопасен и влево и вправо &mdash; это значение бесполезно для криптоаналитика.
    </dd>
    <br/>
    
    <dt>Расшифрование</dt>
    <dd>
        Генератор BBS инициализируется P и Q (из секретного ключа), их произведением N,
        а также X0, вычисленным по Xt.
        После этого каждый бит шифр-текста суммируется по модулю 2 с выходом генератора.
        <br />
        <br />
        Дешифрование, как и шифрование, реализовано многопоточное.
    </dd>
    <br />
    
    <dt></dt>
    <dd>
        <p><a class="btn btn-primary" href="@Url.Action("Work", "ProbabilisticEncryption")">Приступить!</a></p>
    </dd>
</dl>

Protocols/Views/ProbabilisticEncryption/Index.cshtml
@{
    ViewBag.Title = "Вероятностная криптография";
}

<div class="jumbotron">
    <h1>P-Encrypt</h1>
    <p class="lead">
        Вероятностная криптография на основе генератора псевдослучайных чисел Blum &mdash; Blum &mdash; Shub.
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Шифрование</h2>
        <p>Создавайте секретные ключи, шифруйте с их помощью секреты, а потом расшифровывайте их.</p>
        <p><a class="btn btn-default" href="@Url.Action("Work", "ProbabilisticEncryption")">Приступить! &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Как это работает?</h2>
        <p>Из каких шагов состоит работа, как их выполнять и зачем; что было реализовано и как это посмотреть.</p>
        <p><a class="btn btn-default" href="@Url.Action("Help", "ProbabilisticEncryption")">Подробнее &raquo;</a></p>
    </div>
</div>

Protocols/Views/ProbabilisticEncryption/Work.cshtml
@{
    ViewBag.Title = "Операции";
}

<script type="text/javascript" src="../../Scripts/Work/PEncryptionWork.js"></script>

<div class="jumbotron">
    <h1>P-Encrypt</h1>
    <p class="lead">
        Вероятностная криптография на основе генератора псевдослучайных чисел Blum &mdash; Blum &mdash; Shub.
    </p>
</div>

<div class="bs-callout"
     data-bind="visible: HasResult, css: {'bs-callout-danger': IsResultError, 'bs-callout-success' : !IsResultError() }">
    <h4 data-bind="text: ResultHeader"></h4>
    <p data-bind="html: ResultText"></p>
</div>

<h2>Управление</h2>
<div class="form-horizontal">
    <div class="form-group">
        <label for="ModesContainer" class="col-md-2 control-label">Сторона</label>
        <div id="ModesContainer">
            <div class="col-sm-10">
                <input type="button" class="btn" onclick="setMode('Создать ключ')" value="Создать ключ"
                       data-bind="css: {'btn-primary': IsKeyMode, 'btn-default' : !IsKeyMode() }" />

                <input type="button" class="btn" onclick="setMode('Зашифровать')" value="Зашифровать"
                       data-bind="css: {'btn-primary': IsEncryptMode, 'btn-default' : !IsEncryptMode() }" />
                
                <input type="button" class="btn" onclick="setMode('Расшифровать')" value="Расшифровать"
                       data-bind="css: {'btn-primary': IsDecryptMode, 'btn-default' : !IsDecryptMode() }" />
                
                <a class="btn btn-warning" href="@Url.Action("Help", "ProbabilisticEncryption")">Помощь</a>
            </div>
        </div>
    </div>
    
    <div class="form-group" data-bind="visible: !IsKeyMode()">
        <label for="KeyId" class="col-md-2 control-label">Идентификатор ключа</label>
        <div class="col-sm-10">
            <input type="text" id="KeyId" class="form-control" placeholder="Введите идентификатор" data-bind="value: KeyId">
        </div>
    </div>

    <div class="form-group" data-bind="visible: IsDecryptMode">
        <label for="MessageId" class="col-md-2 control-label">Идентификатор сообщения</label>
        <div class="col-sm-10">
            <input type="text" id="MessageId" class="form-control" placeholder="Введите идентификатор" data-bind="value: MessageId">
        </div>
    </div>
    
    <div class="form-group" data-bind="visible: IsEncryptMode">
        <label for="Message" class="col-md-2 control-label">Текст сообщения</label>
        <div class="col-sm-10">
            <input type="text" id="Message" class="form-control" placeholder="Введите сообщение" data-bind="value: Message">
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-sm-10">
            <input type="button" class="btn btn-success" onclick="process()" data-bind="value: Mode, visible: !Process()"/>
            <img src="../../Content/Load.gif" style="display: none; width: 27px" alt="<Load>" data-bind="visible: Process" />
        </div>
    </div>
</div>

<div data-bind="visible: !IsDecryptMode()">
    <h2 data-bind="text: TableHeader"></h2>
    <div class="form-group">
        <img src="../../Content/Load.gif" style="display: none; width: 27px" alt="<Load>" data-bind="visible: LoadingTable" />
        <table id="Viewer" class="table table-condensed table-hover" data-bind="visible: !LoadingTable()"></table>
    </div>
</div>

<script>
    ko.applyBindings(data);
    setMode("Создать ключ");
</script>